### ISSUE TITLE
Install fails on Mac

### ISSUE THREAD

**Issue by jonbgallant** [Azure/azure-iot-sdk-python#113]
- **OS and version used:** Mac

- **Python runtime used:** Any

- **SDK version used:** Current

# Description of the issue:
No way to use the python SDK on mac.

No package and can't build it.

```
ANDYs-MBP:iot-data-open-hack andyluong$ pip install azure-iothub-service-client
Collecting azure-iothub-service-client
  Could not find a version that satisfies the requirement azure-iothub-service-client (from versions: )
No matching distribution found for azure-iothub-service-client
ANDYs-MBP:iot-data-open-hack andyluong$

```

**Comment by zolvarga** [comment]
@jonbgallant 

Thanks for reporting it. It is a known build issue on Mac.
We are working on the fix.

Zoltan

**Comment by zolvarga** [comment]
@jonbgallant 

The build is fixed. Please try to build it on MAC using the latest master of the Python repo. 

Best Regards,
Zoltan

**Comment by arthuston** [comment]
Still a problem:
$ pip install azure-iothub-service-client
Collecting azure-iothub-service-client
  Could not find a version that satisfies the requirement azure-iothub-service-client (from versions: )
No matching distribution found for azure-iothub-service-client
$ pip --version
pip 10.0.1 from /anaconda3/lib/python3.6/site-packages/pip (python 3.6)
