### ISSUE TITLE
ImportError: libboost_python-py27.so.1.55.0: cannot open shared object file: No such file or directory on raspbian

### ISSUE THREAD

**Issue by eifinger** [Azure/azure-iot-sdk-python#126]
- **OS and version used:** <VERSION> Linux raspberrypi 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux

- **Python runtime used:** <VERSION> Python 2.7.13 and Python 3.5.3

- **SDK version used:** <VERSION> 1.3.0

# Description of the issue:
 import iothub_client fails with the error message seen below

# Code sample exhibiting the issue:
import iothub_client

# Console log of the issue:
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    import iothub_client
  File "/home/pi/.local/lib/python2.7/site-packages/iothub_client/__init__.py"line 1, in <module>
    from .iothub_client import *
ImportError: libboost_python-py27.so.1.55.0: cannot open shared object file: Nsuch file or directory

**Comment by zolvarga** [comment]
@eifinger 

Install boost with the following commands:

sudo apt-get install libboost1.55-all
OR
sudo apt-get install libboost-all-dev
OR
sudo apt-get update
sudo apt-get upgrade

Best Regards,
Zoltan

**Comment by eifinger** [comment]
1. sudo apt-get install libboost1.55-all 
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libboost1.55-all
E: Couldn't find any package by glob 'libboost1.55-all'
E: Couldn't find any package by regex 'libboost1.55-all'
```

2. sudo apt-get install libboost-all-dev
Installs 252MB of libraries, still the same error message

3. sudo apt-get update && upgrade
Newest version, no updates

**Comment by sergiomfsilva** [comment]
Hi all, 

The same issue described above.

I installed the the azure-iothub-device-client using the command:

`pip install azure-iothub-device-client`

After run the sample codes and the same error described:

> ImportError: libboost_python-py34.so.1.55.0: cannot open shared object file

This is because no python 3.4 is installed and because now libboost in RPI is the 1.62 version
`find / -iname *libboost_python*`

> /usr/lib/arm-linux-gnueabihf/libboost_python-py35.a
> /usr/lib/arm-linux-gnueabihf/libboost_python-py27.so.1.62.0
> /usr/lib/arm-linux-gnueabihf/libboost_python.so
> /usr/lib/arm-linux-gnueabihf/libboost_python-py27.so
> /usr/lib/arm-linux-gnueabihf/libboost_python-py35.so.1.62.0
> /usr/lib/arm-linux-gnueabihf/libboost_python.a
> /usr/lib/arm-linux-gnueabihf/libboost_python-py27.a
> /usr/lib/arm-linux-gnueabihf/libboost_python-py35.so

The /usr/local/lib/python3.5/dist-packages/iothub_client/iothub_client.so was compiled with libboost_python-py34.so.1.55.0 library.

To solve or a new pip package is created using the 1.62 library or compiling again from the source:

- on raspberry pi clone the repository like described in https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#linux
- inside build_all/linux make the commands described in same site for python3.5
- /setup.sh --python-version 3.5
- ./build.sh --build-python 3.5

After the iothub_client.so is in azure-iot-sdk-python/device/samples/iothub_client.so and we must do:

`cp azure-iot-sdk-python/device/samples/iothub_client.so /usr/local/lib/python3.5/dist-packages/iothub_client/iothub_client.so`

and problem solved for me.

I never create a pip package but how can I help to produce a new azure-iothub-device-client release  package?

Best regards

**Comment by zaheer308** [comment]
@sergiomfsilva 
Hi
when i apply this command on raspbian
`cp azure-iot-sdk-python/device/samples/iothub_client.so /usr/local/lib/python3.5/dist-packages/iothub_client/iothub_client.so`
i got this 
`cp: cannot create regular file '/usr/local/lib/python3.5/dist-packages/iothub_client/iothub_client.so': No such file or directory`
i tried to create manually directory on raspbian GUI but access denied, 
Urgent help needed

**Comment by sergiomfsilva** [comment]
Hi @zaheer308 

Do not create any folder manually. The command 
pip install azure-iothub-device-client 

or

pip3 install azure-iothub-device-client 

must create the /usr/local/lib/python3.5/dist-packages/iothub_client/ folder for you

Best Regards

**Comment by zaheer308** [comment]
@sergiomfsilva 
i have used following command
`pip install azure-iothub-service-client`

but on python3 , i am getting following error
`>>> import iothub_service_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.5/site-packages/iothub_service_client/__init__.py", line 1, in <module>
    from .iothub_service_client import *
ImportError: libboost_python-py34.so.1.55.0: cannot open shared object file: No such file or directory `

**Comment by zaheer308** [comment]
@sergiomfsilva on using above method as you mentioned and using following command

` sudo cp azure-iot-sdk-python/device/samples/iothub_client.so /usr/local/lib/python3.5/dist-packages/iothub_service_client/iothub_client.so`

getting same error ,

i am new with raspberry pi and linux based system, just want to connect my raspberry with azure iot hub , but stuck with 
`import iothub_service_client`

i am following instructions from [https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-getstarted](url)  

any useful help needed

**Comment by sergiomfsilva** [comment]
@zaheer

you did the next command

sudo cp azure-iot-sdk-python/device/samples/iothub_client.so /usr/local/lib/python3.5/dist-packages/iothub_service_client/iothub_client.so 

or the command 

cp azure-iot-sdk-python/device/samples/iothub_client.so /home/pi/.local/lib/python3.5/site-packages/iothub_service_client/

?

**Comment by zaheer308** [comment]
@sergiomfsilva

i did both commands,

**Comment by zaheer308** [comment]
@eifinger did you resolve the issue on rasspberry , i am still facing it

**Comment by sergiomfsilva** [comment]
@eifinger 

with the procedure described above I solved the issues.

In that procedure I also solved a issue related with openssl library.

In the current week I will install a new RPI and I will make the all procedure again. After I give some feedback.

**Comment by eifinger** [comment]
@sergiomfsilva Yes the issue can be resolved using your described workaround.
But in my eyes until a "pip install" does not work out of the box this issue is unresolved.

**Comment by zaheer308** [comment]
@eifinger  @sergiomfsilva 
i have just solved the error by copy/paste iothub_client.so &  iothub_service_client.so to the same path of my example.py file.

**Comment by sergiomfsilva** [comment]
@zaheer308

If you copy the iothub_client.so & iothub_service_client.so to the same folder and it works and if you copy to 

/usr/local/lib/python3.5/dist-packages/iothub_service_client/

and to 

/usr/local/lib/python3.5/dist-packages/iothub_client/

and it does not work, it's an issue with your python load module path. My proposal is make a fresh RPI install, go to user root(do the command sudo su) and make all steps describe before and see if works. I will do this this afternoon. I will give feedback later.

@eifinger yes also for me is unsolved.  For that someone need to compile, create a new version of the pip package and publish that.

**Comment by sergiomfsilva** [comment]
Hi, 

feedback about installing from scratch

## Enviroment

**OS and version used:** Linux raspberrypi 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux

**Python runtime used:** Python 3.5.3

**SDK version used:** 1.3.1

## Workaround steps used

### Get images and prepare to do the work

- get last Rasbian Lite Image
- flash microSD card for Raspberry Pi3
- boot with raspberry pi
- login with pi user
- make the command
`sudo su`
- go to root folder
`cd /root`

### Update the system and make some time checks

Do the next commands

```
apt-get update && apt-get upgrade
apt-get install ntp
```

Check the RPI date with the command 

`date`

After date ok all its ready

**Note:** Configure ntp.conf file if date issues found.

### Install required packages and review the error reported

- Install required packages
`apt-get install -y git cmake build-essential curl libcurl4-openssl-dev libssl-dev uuid-dev python3-pip`

- Clone SDK
`git clone --recursive https://github.com/Azure/azure-iot-sdk-python.git`

- Install device client package using pip3
`pip3 install azure-iothub-device-client`

- Go to samples folder
`cd azure-iot-sdk-python/device/samples/`

- Run the sample code
`python3 iothub_client_sample.py`

- The error must be the same

```
Traceback (most recent call last):
  File "iothub_client_sample.py", line 10, in <module>
    import iothub_client
  File "/usr/local/lib/python3.5/dist-packages/iothub_client/__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: libboost_python-py34.so.1.55.0: cannot open shared object file: No such file or directory

```

### Build new libraries and apply it

- Go to building folder for linux
`cd /root/azure-iot-sdk-python/build_all/linux`

- Run Setup
`./setup.sh --python-version 3.5`

- Replace openssl dev with gnutls dev already reported like solution for a curl out of memory issue
```
apt remove libcurl4-openssl-dev
apt install libcurl4-gnutls-dev
```

- build libraries
`./build.sh --build-python 3.5`

- Go to root folder
`cd /root`

- Move created library to python iothub_client path
`mv azure-iot-sdk-python/device/samples/iothub_client.so /usr/local/lib/python3.5/dist-packages/iothub_client/iothub_client.so`

- Go to samples folder
`cd azure-iot-sdk-python/device/samples/`

- Run the sample code
`python3 iothub_client_sample.py`

## Conclustion

This solve the issue found and works in the raspberry. 
This did not solve this issue because it is related with the pip package. To solve a new pip package with library and python version updated.

**Comment by zolvarga** [comment]
@eifinger 

Could you please let me know if this issue has been resolved or not?

Best Regards,
Zoltan

**Comment by eifinger** [comment]
That depends, is there a new pip version which works out of the box on raspbian?

**Comment by eifinger** [comment]
Is there an update on this?

**Comment by wladneto** [comment]
I got it in NodeJS...

**Comment by eifinger** [comment]
Congratulations!

**Comment by pierreca** [comment]
@eifinger @wladneto @zaheer308 @sergiomfsilva usually these problems appear when the default version of boost on the system is different from the one we link the SDK against. I just published a new version of the packages (1.4.1) that builds against the default raspbian stretch version - all of you working with raspbian should be good now. can you please confirm?

**Comment by ko5win** [comment]
@pierreca Still having the same problem after pip installing the latest sdk version (1.4.1)

ImportError: libboost_python-py27.so.1.62.0: cannot open shared object file: No such file or directory

**Comment by pierreca** [comment]
@ko5win 
- are you running raspbian stretch or jessie? You probably want *stretch* now. it's the latest stable and that's the one we're testing against.
- is the `libboost-python1.62.0` package installed? if not you can install it with `apt-get install libboost-python1.62.0`. this is the correct version against which the SDK is compiled.

I just installed a fresh raspberry pi with stretch and after installing the proper version of libboost everything works as expected.

**Comment by ko5win** [comment]
@pierreca Can confirm that after reflashing with Raspbian stretch + running `sudo apt-get install libboost-python1.62.0` will make the pip version work, thanks!

**Comment by pierreca** [comment]
@ko5win that's great thanks for confirming! closing as resolved then.

**Comment by az-iot-builder-01** [comment]
@eifinger, @sergiomfsilva, @zaheer308, @wladneto, @ko5win, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)

**Comment by SyedOsman33** [comment]
getting the same error but, i am using virtaulenv how can i fix the issue ?

**Comment by francofs** [comment]
@sergiomfsilva Got the same error using Ubuntu 18 on a Pi and python 2.7. Building from source worked the same way you described, except I didn't have to switch libcurl4 package. What is that for again?

**Comment by pierreca** [comment]
@francofs some older versions of libcurl had a bug that, combined with the C SDK that we wrap around, would cause Out of memory errors. glad to learn it's not needed anymore :)

**Comment by tamlol** [comment]
on raspbian stretch
- install libboost-python1.62.0 package with apt-get install libboost-python1.62.0
- pip3 install azure-iothub-device-client
- python3 test.py

raspbian buster
- copy libboost_python and libcurl from raspbian stretch to /usr/lib/arm-linux-gnueabihf on raspbian-buster. and It work for me.

**Comment by millena7** [comment]
Hi!

I'm with the same problem when I try to import iothub_client

**ImportError: libboost_python-py35.so.1.62.0: cannot open shared object file: No such file or directory**

Raspbian buster
Python 3.7.3

It is installed libboost-python1.62.0

Could you help me please?
